name: Full-Stack CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
      - name: Run tests
        run: npm test
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: frontend
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: backend
      - name: Run tests
        run: npm test
        working-directory: backend
      - name: Lint check
        run: npm run lint
        working-directory: backend
  database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
        working-directory: backend
      - name: Apply database migrations
        run: npx sequelize-cli db:migrate
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

